---
language: node_js
node_js:
  - "8"

services:
  - xvfb

addons:
  firefox: latest
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fail_fast: true

  include:
    # runs linting and tests with current locked deps

    - stage: "Tests"
      name: "Tests"
      install:
        - yarn install --non-interactive
      script:
        - yarn lint:hbs
        - yarn lint:js
        - yarn test

    - name: "Floating Dependencies"
      script:
        - yarn test

    - stage: "Additional Tests"
      env: EMBER_TRY_SCENARIO=ember-lts-2.18
    - env: EMBER_TRY_SCENARIO=ember-lts-3.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-default-lazy
    - env: EMBER_TRY_SCENARIO=ember-default-with-jquery
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.46
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.47
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.48
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.49
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.50
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.51
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.52
    - env: EMBER_TRY_SCENARIO=ember-default-mapbox-gl-0.53

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
